"""Alembic migration revision template."""
revision: str = "71e37dd2f7b3"
down_revision: str | None = "010"
branch_labels: str | None = None
depends_on: str | None = None


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.alter_column('agent_memories', 'agent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to agents.id',
               existing_nullable=False)
    op.alter_column('agent_memories', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='Role if this is a conversation memory: user, assistant, system',
               existing_comment='Role if conversation memory: user, assistant, system',
               existing_nullable=True)
    op.alter_column('agent_memories', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Optional TTL — memory is eligible for pruning after this time',
               existing_comment='Optional TTL for memory pruning',
               existing_nullable=True)
    op.alter_column('agent_runs', 'agent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to agents.id',
               existing_nullable=False)
    op.alter_column('agent_runs', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('agent_tools', 'agent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to agents.id',
               existing_nullable=False)
    op.alter_column('agent_tools', 'tool_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tool type identifier: knowledge_search, document_reader, task_manager, global_search, chat_history, calculator, current_time',
               existing_comment='Tool type identifier',
               existing_nullable=False)
    op.alter_column('agent_tools', 'description',
               existing_type=sa.TEXT(),
               comment='Description of what this tool does (used by the agent to decide when to use it)',
               existing_comment='Description of what this tool does',
               existing_nullable=True)
    op.alter_column('agent_tools', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Tool-specific configuration (e.g. kb_id, max_results)',
               existing_comment='Tool-specific configuration',
               existing_nullable=True)
    op.alter_column('agents', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('agents', 'model',
               existing_type=sa.VARCHAR(length=100),
               comment='AI model identifier (e.g. gpt-4o, claude-3-opus)',
               existing_comment='AI model identifier',
               existing_nullable=False,
               existing_server_default=sa.text("'gpt-4o'::character varying"))
    op.alter_column('document_analysis', 'file_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to files.id (one-to-one)',
               existing_nullable=False)
    op.alter_column('document_analysis', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_document_analysis_file'), 'document_analysis', type_='unique')
    op.alter_column('document_chunks', 'file_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to files.id',
               existing_nullable=False)
    op.alter_column('document_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_metadata', 'file_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to files.id (one-to-one)',
               existing_nullable=False)
    op.alter_column('document_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_document_metadata_file'), 'document_metadata', type_='unique')
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(length=512),
               comment='Original filename',
               existing_nullable=False)
    op.alter_column('files', 'mime_type',
               existing_type=sa.VARCHAR(length=128),
               comment='MIME type (e.g. image/png)',
               existing_nullable=False)
    op.alter_column('files', 'size_bytes',
               existing_type=sa.BIGINT(),
               comment='File size in bytes',
               existing_nullable=False)
    op.alter_column('files', 'storage_path',
               existing_type=sa.VARCHAR(length=1024),
               comment='Path returned by the storage provider',
               existing_nullable=False)
    op.alter_column('files', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               comment='Processing status: uploaded, queued, processing, completed, failed',
               existing_comment='Processing status: pending, processing, completed, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))
    op.alter_column('files', 'is_temporary',
               existing_type=sa.BOOLEAN(),
               comment='Whether the file can be garbage-collected',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_documents', 'knowledge_base_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to knowledge_bases.id',
               existing_nullable=False)
    op.alter_column('kb_documents', 'file_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Optional FK to files.id',
               existing_nullable=True)
    op.alter_column('kb_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_kb_documents_kb_id'), table_name='kb_documents')
    op.create_index(op.f('ix_kb_documents_knowledge_base_id'), 'kb_documents', ['knowledge_base_id'], unique=False)
    op.alter_column('kb_embeddings', 'kb_document_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to kb_documents.id',
               existing_nullable=False)
    op.alter_column('kb_embeddings', 'knowledge_base_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to knowledge_bases.id (denormalised for search perf)',
               existing_nullable=False)
    op.alter_column('kb_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment='pgvector embedding vector',
               existing_nullable=False)
    op.drop_index(op.f('ix_kb_embeddings_embedding_hnsw'), table_name='kb_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('knowledge_bases', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recent_searches', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('saved_searches', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('task_attachments', 'task_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to tasks.id',
               existing_nullable=False)
    op.alter_column('task_attachments', 'file_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to files.id',
               existing_nullable=False)
    op.alter_column('task_attachments', 'uploaded_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('task_comments', 'task_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to tasks.id',
               existing_nullable=False)
    op.alter_column('task_comments', 'author_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('task_comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_labels', 'task_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to tasks.id',
               existing_nullable=False)
    op.alter_column('tasks', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'two_factor_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Whether two-factor authentication is enabled (reserved for future use)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of the most recent successful login',
               existing_nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of the most recent successful login',
               existing_nullable=True)
    op.alter_column('users', 'two_factor_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether two-factor authentication is enabled (reserved for future use)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'owner_id',
               existing_type=sa.UUID(),
               comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('task_labels', 'task_id',
               existing_type=sa.UUID(),
               comment='FK to tasks.id',
               existing_nullable=False)
    op.alter_column('task_comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_comments', 'author_id',
               existing_type=sa.UUID(),
               comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('task_comments', 'task_id',
               existing_type=sa.UUID(),
               comment='FK to tasks.id',
               existing_nullable=False)
    op.alter_column('task_attachments', 'uploaded_by',
               existing_type=sa.UUID(),
               comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('task_attachments', 'file_id',
               existing_type=sa.UUID(),
               comment='FK to files.id',
               existing_nullable=False)
    op.alter_column('task_attachments', 'task_id',
               existing_type=sa.UUID(),
               comment='FK to tasks.id',
               existing_nullable=False)
    op.alter_column('saved_searches', 'owner_id',
               existing_type=sa.UUID(),
               comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('recent_searches', 'owner_id',
               existing_type=sa.UUID(),
               comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_bases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_bases', 'user_id',
               existing_type=sa.UUID(),
               comment='FK to users.id',
               existing_nullable=False)
    op.create_index(op.f('ix_kb_embeddings_embedding_hnsw'), 'kb_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('kb_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment=None,
               existing_comment='pgvector embedding vector',
               existing_nullable=False)
    op.alter_column('kb_embeddings', 'knowledge_base_id',
               existing_type=sa.UUID(),
               comment='FK to knowledge_bases.id (denormalised for search perf)',
               existing_nullable=False)
    op.alter_column('kb_embeddings', 'kb_document_id',
               existing_type=sa.UUID(),
               comment='FK to kb_documents.id',
               existing_nullable=False)
    op.drop_index(op.f('ix_kb_documents_knowledge_base_id'), table_name='kb_documents')
    op.create_index(op.f('ix_kb_documents_kb_id'), 'kb_documents', ['knowledge_base_id'], unique=False)
    op.alter_column('kb_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_documents', 'file_id',
               existing_type=sa.UUID(),
               comment='Optional FK to files.id',
               existing_nullable=True)
    op.alter_column('kb_documents', 'knowledge_base_id',
               existing_type=sa.UUID(),
               comment='FK to knowledge_bases.id',
               existing_nullable=False)
    op.alter_column('files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('files', 'is_temporary',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the file can be garbage-collected',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('files', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               comment='Processing status: pending, processing, completed, failed',
               existing_comment='Processing status: uploaded, queued, processing, completed, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))
    op.alter_column('files', 'storage_path',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='Path returned by the storage provider',
               existing_nullable=False)
    op.alter_column('files', 'size_bytes',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='File size in bytes',
               existing_nullable=False)
    op.alter_column('files', 'mime_type',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='MIME type (e.g. image/png)',
               existing_nullable=False)
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Original filename',
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_document_metadata_file'), 'document_metadata', ['file_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('document_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_metadata', 'file_id',
               existing_type=sa.UUID(),
               comment='FK to files.id (one-to-one)',
               existing_nullable=False)
    op.alter_column('document_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_chunks', 'file_id',
               existing_type=sa.UUID(),
               comment='FK to files.id',
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_document_analysis_file'), 'document_analysis', ['file_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('document_analysis', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_analysis', 'file_id',
               existing_type=sa.UUID(),
               comment='FK to files.id (one-to-one)',
               existing_nullable=False)
    op.alter_column('agents', 'model',
               existing_type=sa.VARCHAR(length=100),
               comment='AI model identifier',
               existing_comment='AI model identifier (e.g. gpt-4o, claude-3-opus)',
               existing_nullable=False,
               existing_server_default=sa.text("'gpt-4o'::character varying"))
    op.alter_column('agents', 'owner_id',
               existing_type=sa.UUID(),
               comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('agent_tools', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Tool-specific configuration',
               existing_comment='Tool-specific configuration (e.g. kb_id, max_results)',
               existing_nullable=True)
    op.alter_column('agent_tools', 'description',
               existing_type=sa.TEXT(),
               comment='Description of what this tool does',
               existing_comment='Description of what this tool does (used by the agent to decide when to use it)',
               existing_nullable=True)
    op.alter_column('agent_tools', 'tool_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tool type identifier',
               existing_comment='Tool type identifier: knowledge_search, document_reader, task_manager, global_search, chat_history, calculator, current_time',
               existing_nullable=False)
    op.alter_column('agent_tools', 'agent_id',
               existing_type=sa.UUID(),
               comment='FK to agents.id',
               existing_nullable=False)
    op.alter_column('agent_runs', 'owner_id',
               existing_type=sa.UUID(),
               comment='FK to users.id',
               existing_nullable=False)
    op.alter_column('agent_runs', 'agent_id',
               existing_type=sa.UUID(),
               comment='FK to agents.id',
               existing_nullable=False)
    op.alter_column('agent_memories', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Optional TTL for memory pruning',
               existing_comment='Optional TTL — memory is eligible for pruning after this time',
               existing_nullable=True)
    op.alter_column('agent_memories', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='Role if conversation memory: user, assistant, system',
               existing_comment='Role if this is a conversation memory: user, assistant, system',
               existing_nullable=True)
    op.alter_column('agent_memories', 'agent_id',
               existing_type=sa.UUID(),
               comment='FK to agents.id',
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
