"""Pydantic schemas for the AI Task Assistant.

All request/response types for AI-powered task operations: natural-language
task generation, subtask suggestions, effort estimation, priority/due-date
recommendations, work summaries, and cross-feature conversions.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field


# ── Generate tasks from natural language ──────────────────────────────────────


class AITaskGenerationRequest(BaseModel):
    """Natural-language input for AI task extraction."""

    text: str = Field(
        ...,
        min_length=1,
        max_length=50000,
        description="Natural language text describing tasks to create",
    )
    context: str | None = Field(
        None,
        max_length=20000,
        description="Optional additional context (project, goals, constraints)",
    )


class AITaskDraft(BaseModel):
    """A single task suggestion generated by the AI."""

    title: str = Field(..., description="Suggested task title")
    description: str | None = Field(None, description="Suggested description")
    priority: str = Field(default="medium", description="Suggested priority")
    estimated_minutes: int | None = Field(None, description="Suggested effort")
    due_date: datetime | None = Field(None, description="Suggested due date")
    labels: list[str] = Field(default_factory=list, description="Suggested label names")


class AITaskGenerationResponse(BaseModel):
    """Response from AI task generation."""

    tasks: list[AITaskDraft] = Field(
        default_factory=list,
        description="Suggested task drafts created from input text",
    )


# ── Subtasks ──────────────────────────────────────────────────────────────────


class AISubtaskRequest(BaseModel):
    """Request to generate subtasks for an existing task."""

    task_id: UUID = Field(..., description="ID of the parent task")
    count: int | None = Field(
        None,
        ge=1,
        le=20,
        description="Desired number of subtasks (AI will decide if omitted)",
    )


class AISubtaskItem(BaseModel):
    """A single subtask suggestion."""

    title: str = Field(..., description="Subtask title")
    description: str | None = Field(None, description="Subtask details")
    estimated_minutes: int | None = Field(None, description="Effort estimate")


class AISubtaskResponse(BaseModel):
    """Response from subtask generation."""

    subtasks: list[AISubtaskItem] = Field(
        default_factory=list,
        description="Suggested subtasks",
    )


# ── Effort estimation ─────────────────────────────────────────────────────────


class AIEffortEstimateRequest(BaseModel):
    """Request to estimate effort for a task."""

    task_id: UUID = Field(..., description="ID of the task to estimate")


class AIEffortEstimateResponse(BaseModel):
    """Effort estimation result."""

    estimated_minutes: int = Field(
        ...,
        ge=1,
        description="Estimated effort in minutes",
    )
    confidence: str = Field(
        ...,
        description="Confidence level: high, medium, low",
    )
    reasoning: str | None = Field(
        None,
        description="Brief explanation of the estimate",
    )


# ── Priority / due-date suggestion ────────────────────────────────────────────


class AIPrioritySuggestionRequest(BaseModel):
    """Request for priority and due-date suggestions."""

    task_id: UUID = Field(..., description="ID of the task")


class AIPrioritySuggestionResponse(BaseModel):
    """Priority and due-date recommendation."""

    priority: str = Field(..., description="Suggested priority")
    due_date: datetime | None = Field(None, description="Suggested due date")
    reasoning: str | None = Field(
        None,
        description="Brief explanation of the suggestion",
    )


# ── Work summary ──────────────────────────────────────────────────────────────


class AISummaryRequest(BaseModel):
    """Request to summarise completed work in a date range."""

    start_date: datetime | None = Field(
        None,
        description="Start of range (defaults to start of current week)",
    )
    end_date: datetime | None = Field(
        None,
        description="End of range (defaults to now)",
    )


class AISummaryResponse(BaseModel):
    """AI-generated work summary."""

    summary: str = Field(
        ...,
        max_length=10000,
        description="Markdown-formatted summary of completed work",
    )
    total_completed: int = Field(
        default=0,
        description="Number of tasks completed in the period",
    )
    highlights: list[str] = Field(
        default_factory=list,
        description="Key accomplishments extracted by the AI",
    )


# ── Chat-to-task conversion ───────────────────────────────────────────────────


class AIConvertChatRequest(BaseModel):
    """Request to convert a chat conversation into a task."""

    conversation_id: UUID = Field(
        ...,
        description="ID of the chat conversation to convert",
    )


class AIConvertChatResponse(BaseModel):
    """Result of chat-to-task conversion."""

    task: AITaskDraft = Field(
        ...,
        description="Suggested task derived from the conversation",
    )
    key_points: list[str] = Field(
        default_factory=list,
        description="Key action items extracted from the chat",
    )


# ── Document-to-task conversion ───────────────────────────────────────────────


class AIConvertDocumentRequest(BaseModel):
    """Request to convert a knowledge-base document into a task."""

    document_id: UUID = Field(
        ...,
        description="ID of the KB document to convert",
    )


class AIConvertDocumentResponse(BaseModel):
    """Result of document-to-task conversion."""

    task: AITaskDraft = Field(
        ...,
        description="Suggested task derived from the document",
    )
    key_points: list[str] = Field(
        default_factory=list,
        description="Key action items extracted from the document",
    )


# ── Next-action generation ────────────────────────────────────────────────────


class AINextActionItem(BaseModel):
    """A single next-action suggestion."""

    title: str = Field(..., description="Suggested next action")
    context: str | None = Field(
        None,
        description="Why this action is suggested",
    )
    source_task_id: UUID | None = Field(
        None,
        description="Related task, if any",
    )
    priority: str = Field(
        default="medium",
        description="Suggested priority for this action",
    )


class AINextActionsResponse(BaseModel):
    """Generated next-action suggestions."""

    actions: list[AINextActionItem] = Field(
        default_factory=list,
        description="Suggested next actions based on current task state",
    )
    summary: str | None = Field(
        None,
        description="Brief overview of the recommendations",
    )
